
services:
  mc-java:
    image: mc-java-custom:1.1
    container_name: mc-java
    ports:
      - "25565:25565"
    environment:
      EULA: "TRUE"
      MEMORY: "2G"
    volumes:
      - java_world:/data
      - ./scripts:/scripts
    restart: unless-stopped

  mc-bedrock:
    image: mc-bedrock-custom:1.1
    container_name: mc-bedrock
    ports:
      - "19132:19132/udp"
    environment:
      EULA: "TRUE"
      MEMORY: "2G"
    volumes:
      - bedrock_world:/data
      - ./scripts:/scripts
    restart: unless-stopped

  mc-admin:
    image: mc-admin-custom:1.3
    container_name: mc-admin
    stdin_open: true
    tty: true
    volumes:
      - java_world:/java_world
      - bedrock_world:/bedrock_world
      - ./scripts:/shared-scripts
      - ./backups:/backups
    restart: unless-stopped

volumes:
  java_world:
  bedrock_world:

