
services:
  minecraft-java:
    image: itzg/minecraft-server
    container_name: mcj-server
    ports:
      - "25565:25565"
    environment:
      EULA: ${EULA}
      TYPE: ${TYPE}
      VERSION: ${VERSION}
      MEMORY: ${MEMORY}
      DIFFICULTY: ${DIFFICULTY}
      MODE: ${MODE}
      MOTD: ${MOTD}
      TZ: ${TZ}
      ENABLE_RCON: ${ENABLE_RCON}
      RCON_PASSWORD: ${RCON_PASSWORD}
    volumes:
      - ./java/data:/data
    restart: unless-stopped
# Uncomment the following section to enable a Bedrock server
# Cannot run Bedrock and Geyser at the same time
#  minecraft-bedrock:
#    image: itzg/minecraft-bedrock-server
#    container_name: mcb-server
#    ports:
#      - "19132:19132/udp"
#    environment:
#      EULA: ${EULA}
#      DIFFICULTY: ${DIFFICULTY}
#      MOTD: ${MOTD}
#      TZ: ${TZ}
#    volumes:
#      - ./bedrock/data:/data
#    restart: unless-stopped
  minecraft-admin:
  # This service is used for administrative tasks and scripts
  # It mounts the scripts and data directories for both Java and Bedrock servers
  # and runs a lightweight Alpine container to keep the environment ready for admin tasks
  # It does not run a Minecraft server but provides a persistent environment for management
    image: alpine
    container_name: mc-admin-server
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./scripts:/scripts
      - ./java/data:/java_data:ro
      - ./bedrock/data:/bedrock_data:ro
    restart: unless-stopped
  
  # GeyserMC service for bridging Java and Bedrock editions
  # This service allows Bedrock clients to connect to the Java server
  # It uses the nefald/geyser image and mounts a configuration directory
  # Cannot run Bedrock and Geyser at the same time.
  geyser:
    image: nefald/geyser:latest
    container_name: geyser
    restart: unless-stopped
    ports:
      - "19132:19132/udp"
    volumes:
      - ./geyser/config:/config