# This docker-compose file is used to set up the Libation server
# It includes a named volume for books and mounts local configuration files
# Ensure to keep the config files up-to-date for proper server operation

services:
  libation-server:
    container_name: libation-server
    image: rmcrackan/libation:latest 
    volumes:
      # Local config files, read-only
      - ./config:/config
      # Named volumes for books.
      - libation_books:/data
    restart: unless-stopped

volumes:
  libation_books:
    name: libation_books
