# Useing itzg's Minecraft Java image
FROM itzg/minecraft-bedrock-server

# Copy local server config files to container directory
# This sets starting defaults for new servers.
COPY server.properties /config/server.properties
COPY whitelist.json /config/whitelist.json
COPY permissions.json /config/permissions.json

