services:
  freshrss:
    container_name: linkding
    image: sissbruecker/linkding:1.45.0
    restart: always
    environment:
      - CRON_MIN=1,31
      - TZ=Europe/London
    volumes:
      - linkding_data:/etc/linkding/data
    ports:
      - "8092:9090"
        # Default port for Linkding web interface is 9090:9090; Changed to avoid conflict with other services
    networks:
      - default
      - shared

volumes:
  linkding_data:
    name: linkding_data
networks:
  default:
    name: linkding_network
  shared:
    name: npmnet
    external: true


