services:
  freshrss:
    container_name: freshrss
    image: freshrss/freshrss
    restart: always
    environment:
      - CRON_MIN=1,31
      - TZ=Europe/London
    volumes:
      - freshrss_data:/var/www/FreshRSS/data
      - freshrss_extensions:/var/www/FreshRSS/extensions
    ports:
      - 8091:80
        # Default port for FreshRSS web interface is 8080:80; Changed to avoid conflict with other services
    networks:
      - default
      - shared

volumes:
  freshrss_data:
    name: freshrss_data
  freshrss_extensions:
    name: freshrss_extensions
networks:
  default:
    name: freshrss_network
  shared:
    name: npmnet
    external: true


