services:
  uptime-kuma:
    container_name: uptime-kuma
    image: louislam/uptime-kuma:2
    restart: unless-stopped
    volumes:
      - ./data:/app/data
      # Read-only access to Docker for monitoring containers.
      # Ok for lab, not for production.
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      # <Host Port>:<Container Port>
      - "3001:3001"